"""empty message

Revision ID: 7061cd16207a
Revises: 
Create Date: 2023-11-20 08:58:40.113967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7061cd16207a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_learning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.String(), nullable=True),
    sa.Column('response_text', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_learning')
    # ### end Alembic commands ###
